# accepted list of countries

countries = [
    # Africa	Central Africa
    # Africa	Northern Africa
    "DJI",
    "ERI",
    "KEN",
    "SOM",
    "TZA",
    # Africa	Indian Ocean
    "COM",
    "MDG",
    "MUS",
    "MYT",
    "REU",
    "SYC",
    # Africa	Northern Africa
    # Africa	Southern Africa
    "MWI",
    "MOZ",
    "ZAF",
    "SWZ",
    "ZWB",
    # Africa	Western Africa
    # Americas	Central America
    "BLZ",
    "CRI",
    "SLV",
    "GTM",
    "HND",
    "MEX",
    "NIC",
    "PAN",
    # Americas	North America
    "CAN",
    "GRL",
    "SPM",
    "USA",
    # Americas	South America
    "COL",
    "GUF",
    "GUY",
    "SUR",
    "VEN",
    # Americas	West Indies
    "AIA",
    "ATG",
    "ABW",
    "BHS",
    "BRB",
    "BMU",
    "VGB",
    "CYM",
    "CUB",
    "DMA",
    "DOM",
    "GRD",
    "GLP",
    "HTI",
    "JAM",
    "MTQ",
    "MSR",
    "ANT",
    "PRI",
    "KNA",
    "LCA",
    "VCT",
    "TTO",
    "TCA",
    "VIR",
    # Asia	Central Asia
    # Asia	East Asia
    "CHN",
    "JPN",
    "PRK",
    "KOR",
    "TWN",
    # Asia	Northern Asia
    # Asia	South Asia
    "BGD",
    "IND",
    "MDV",
    "PAK",
    "LKA",
    # Asia	South East Asia
    "BRN",
    "KHM",
    "CXR",
    "CCK",
    "IDN",
    "LAO",
    "MYS",
    "MMR",
    "PHL",
    "SGP",
    "THA",
    "VNM",
    # Asia	South West Asia
    "BHR",
    "IRN",
    "KWT",
    "OMN",
    "QAT",
    "SAU",
    "YEM",
    # Europe
    # Oceania	Pacific
    "ASM",
    "AUS",
    "COK",
    "FJI",
    "PYF",
    "GUM",
    "KIR",
    "MHL",
    "FSM",
    "NRU",
    "NCL",
    "NZL",
    "NIU",
    "NFK",
    "MNP",
    "PLW",
    "PNG",
    "PCN",
    "SLB",
    "TKL",
    "TON",
    "TUV",
    "VUT",
    "WLF",
    "WSM",
]

NAME_1_exclusion = [
    # Canada
    "Alberta",
    "British Columbia",
    "Northwest Territories",
    "Nunavut",
    "Ontario",
    "Saskatchewan",
    "Yukon",
    # Colombia
    "Amazonas",
    "Apure",
    "Arauca",
    "Bogotá D.C.",
    "Boyacá",
    "Caldas",
    "Caquetá",
    "Casanare",
    "Cauca",
    "Cundinamarca",
    "Guainía",
    "Guaviare",
    "Huila",
    "Meta",
    "Nariño",
    "Putumayo",
    "Quindío",
    "Risaralda",
    "Santander",
    "Tolima",
    "Valle del Cauca",
    "Vaupés",
    "Vichada",
    # China
    "Chongqing",
    "Gansu",
    "Guizhou",
    "Henan",
    "Hubei",
    "Hunan",
    "Nei Mongol",
    "Ningxia Hui",
    "Qinghai",
    "Shaanxi",
    "Sichuan",
    "Xinjiang Uygur",
    "Xizang",
    "Yunnan",
    # Greenlan
    "Qaasuitsup",
    "Northeast Greenland National Par"
    # India
    "Federally Administered Tribal Ar",
    "Khyber-Pakhtunkhwa",
    "Chandigarh",
    "Haryana",
    "Himachal Pradesh",
    "Punjab",
    "Uttar Pradesh",
    "Uttarakhand",
    # Iran
    "Alborz",
    "Ardebil",
    "East Azarbaijan",
    "Esfahan",
    "Gilan",
    "Golestan",
    "Hamadan",
    "Ilam",
    "Kermanshah",
    "Kordestan",
    "Lorestan",
    "Markazi",
    "Mazandaran",
    "North Khorasan",
    "Qazvin",
    "Qom",
    "Razavi Khorasan",
    "Semnan",
    "South Khorasan",
    "Tehran",
    "West Azarbaijan",
    "Yazd",
    "Zanjan",
    # Saudi Arabia
    "'Asir",
    "Al Bahah",
    "Al Hudud ash Shamaliyah",
    "Al Jawf",
    "Al Madinah",
    "Al Qassim",
    "Ar Riyad",
    "Ḥaʼil",
    "Makkah",
    "Najran",
    "Tabuk",
    # US
    "Alaska",
    "Arizona",
    "Arkansas",
    "Colorado",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Manitoba",
    "Michigan",
    "Minnesota",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Mexico",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "South Dakota",
    "Tennessee",
    "Utah",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
]